need on valmis

diff --git a/praks1/lisa_kasutaja b/praks1/lisa_kasutaja
--- a/praks1/lisa_kasutaja
+++ b/praks1/lisa_kasutaja
@@ -1,38 +1,27 @@
 #!/bin/bash
+# Skript loob kasutaja, määrab kodukataloogi ja seab vaikimisi shelliks Bash
 
-# Kontrollime, kas kasutajanimi on sisestatud
-if [ -z "$1" ]; then
-  echo "Kasutajanimi puudub! Kasutamine: ./lisa_kasutaja <kasutajanimi>"
-  exit 1
+# Kontrollime, kas kasutajanimi on sisendina antud
+if [ $# -eq 0 ]; then
+    echo "Viga: kasutajanimi on puudu."
+    echo "Kasutamine: $0 <kasutajanimi>"
+    exit 1
 fi
 
-# Määrame muutujaks kasutajanime
-KASUTAJANIMI=$1
+kasutajanimi="$1"
 
-# Kontrollime, kas kasutaja juba eksisteerib
-if id "$KASUTAJANIMI" &>/dev/null; then
-  echo "Kasutaja '$KASUTAJANIMI' juba eksisteerib!"
-  exit 1
-fi
-
-# Loome kasutaja koos kodukataloogiga
-sudo useradd -m -d /home/$KASUTAJANIMI $KASUTAJANIMI
+# Loome kasutaja, määrame kodukataloogi ja vaikimisi shelliks Bash
+useradd -m -d "/home/$kasutajanimi" -s /bin/bash "$kasutajanimi"
 
 # Kontrollime, kas kasutaja loodi edukalt
 if [ $? -eq 0 ]; then
-  echo "Kasutaja '$KASUTAJANIMI' loodi edukalt."
+    echo "Kasutaja nimega $kasutajanimi on lisatud süsteemi"
+    # Näitame kasutaja infot /etc/passwd failist
+    grep "^$kasutajanimi:" /etc/passwd
+    # Näitame kodukataloogi sisu detailselt
+    echo "kokku $(du -s /home/$kasutajanimi | cut -f1)"
+    ls -la "/home/$kasutajanimi"
 else
-  echo "Kasutaja loomine ebaõnnestus."
-  exit 1
+    echo "Kasutaja '$kasutajanimi' loomine ebaõnnestus."
+    exit 2
 fi
-
-# Loome vajalikud peidetud failid kasutaja kodukataloogi
-sudo -u $KASUTAJANIMI touch /home/$KASUTAJANIMI/.bashrc
-sudo -u $KASUTAJANIMI touch /home/$KASUTAJANIMI/.profile
-sudo -u $KASUTAJANIMI touch /home/$KASUTAJANIMI/.bash_logout
-
-# Kontrollime loodud kodukataloogi ja failide struktuuri
-echo "Kontrollime loodud kodukataloogi:"
-ls -la /home/$KASUTAJANIMI
-
-echo "Kasutaja '$KASUTAJANIMI' on edukalt loodud koos vajalike peidetud failidega!"
